### ISSUE TITLE
UnitTest: Use of unpublished appender "SciTEStdout"

### ISSUE THREAD

**Issue by hoppfrosch** [Lexikos/Object.ahk#1]
Trying to update the submodules, leads to the following:

` git submodule update --init --recursive`
` Submodule 'Yunit' (git@github.com:Lexikos/Yunit.git) registered for path 'Lib/Yunit'`
` Cloning into 'C:/Users/jok/Projects/AHK/Object.ahk/Lib/Yunit'...`
`error: Server does not allow request for unadvertised object a40e97d8eb752f4a5e1fdb0981d81a5cffc315a0`
`Fetched in submodule path 'Lib/Yunit', but it did not contain a40e97d8eb752f4a5e1fdb0981d81a5cffc315a0. Direct fetching of that commit failed.`

Having a closer look at YUnit, this commit does not exist.

You're using an YUnit-appender named "SciTEStdout" within your module `Object_test.ahk`:
`Yunit.Use(SciTEStdout).Test(Tests)`

And indeed: appender "SciTEStdout" does not exist within YUnit-Repository.

Obviously you're using an unpublished version of YUnit.

**Comment by Lexikos** [comment]
I merely forgot to push the subunit. Lexikos/Yunit@a40e97d8 is up now.

> And indeed: appender "SciTEStdout" does not exist within YUnit-Repository.

It's in Object_test.ahk...

**Comment by hoppfrosch** [comment]
OK - after updating the submodule to the latest provided version, the Unittests are running and reporting their output to SCITE-console
