### ISSUE TITLE
UnitTest: Unittests do not work

### ISSUE THREAD

**Issue by hoppfrosch** [Lexikos/Object.ahk#2]
As a followup of #1 I locally changed the appender used in your UnitTest-Module `Object_test.ahk` from unpublished appender `SciTEStdout` to `YunitWindow` (standard YUnit appender).
Running the UnitTest-Module `Object_test.ahk`  leads to the following error:

`Error - Object_test.ahk`
`Error: Missing class object for "new" operator.`
`	Line#`
`	025:          instance.Modules := []`
`	026:          for k,module in instance.base.Modules`
`--->	027:              instance.Modules[k] := new module(instance)`
`	028:          while (A_Index <= classes.Length())`
`	029:          {`
`Call stack:`
`	Yunit.ahk (27) : Yunit.Test`
`	Object_test.ahk (9) : (main)`
`The current thread will exit.`

**Comment by Lexikos** [comment]
You already know that you're using a different version of Yunit. Why open a second issue?

Object.Override.ahk is not compatible with the original Yunit, hence Lexikos/Yunit@a40e97d.

**Comment by hoppfrosch** [comment]
I opened a second issue as I assumed your SciTEStdout  appender works as a standard YUnit-appender (and is compatible with original YUnit) - and therefore I assumed any other appender should work to catch the result of the unit tests ....

Thanks for your comments

**Comment by hoppfrosch** [comment]
Modifying the provided appenders from YUnit according your "SciTEStdout" appender makes those appenders work as well ...
